### ISSUE TITLE
Weights

### ISSUE THREAD

**Issue by fakerybakery** [balisujohn/tortoise.cpp#1]
> Note that the pre loaded ggml-model.bin saved in this repository does not have all the tensors currently loaded by the program, since the version with a lot of tensors is too big to put in version control. Feel free to make an issue asking for the conversion script if you want me to hurry up in posting it.

Hi,
Thank you so much for working on this! I was wondering if you might be able to post the conversion scripts, and also to post the full weights on Hugging Face.
Thank you!

**Comment by balisujohn** [comment]
Thanks for your interest in this project! I'll try to get the weights on huggingface and the modified tortoise repo with the conversion script posted tomorrow.

**Comment by balisujohn** [comment]
All done, see the README for instructions!

**Comment by fakerybakery** [comment]
Thank you!
