### ISSUE TITLE
cloning fails

### ISSUE THREAD

**Issue by trappedinspacetime** [balisujohn/tortoise.cpp#17]
First of all, thank you for developing this project. I wanted to play with it but cloning fails:

          git clone --recurse-submodules https://github.com/balisujohn/tortoise.cpp
          Cloning into 'tortoise.cpp'...
          remote: Enumerating objects: 3615, done.
          remote: Counting objects: 100% (472/472), done.
          remote: Compressing objects: 100% (165/165), done.
          remote: Total 3615 (delta 313), reused 449 (delta 298), pack-reused 3143
          Receiving objects: 100% (3615/3615), 42.77 MiB | 3.71 MiB/s, done.
          Resolving deltas: 100% (2452/2452), done.
          Submodule 'ggml' (git@github.com:ggerganov/ggml.git) registered for path 'ggml'
          Cloning into '/home/***/tortoise.cpp/ggml'...
          The authenticity of host 'github.com (140.82.121.3)' can't be established.
          ED25519 key fingerprint is SHA256:+DiY3wvvV6TuJJhbpZisF/zLDA0zPMSvHdkr4UvCOqU.
          This key is not known by any other names
          Are you sure you want to continue connecting (yes/no/[fingerprint])?

**Comment by balisujohn** [comment]
I don't think this is a problem with the repo, it's either a problem with github or your local ssh setup.

**Comment by balisujohn** [comment]
Use this command instead:
````
git clone --recursive git@github.com:balisujohn/tortoise.cpp.git
````

**Comment by trappedinspacetime** [comment]
@balisujohn 

        git clone --recursive git@github.com:balisujohn/tortoise.cpp.git
        Cloning into 'tortoise.cpp'...
        The authenticity of host 'github.com (140.82.121.3)' can't be established.
        ED25519 key fingerprint is SHA256:+DiY3wvvV6TuJJhbpZisF/zLDA0zPMSvHdkr4UvCOqU.
        This key is not known by any other names
        Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
        Warning: Permanently added 'github.com' (ED25519) to the list of known hosts.
        git@github.com: Permission denied (publickey).
        fatal: Could not read from remote repository.
        
        Please make sure you have the correct access rights
        and the repository exists.

**Comment by balisujohn** [comment]
Maybe useful for troubleshooting

https://docs.github.com/en/authentication/troubleshooting-ssh/error-permission-denied-publickey

**Comment by baileyheading** [comment]
I had the same issue too and I had to setup my ssh public keys and stuff to fix it @trappedinspacetime. I didn't have this issue with other repos @balisujohn as far as I can remember but perhaps you have a more secure setting or something?

**Comment by Green-Sky** [comment]
The reason this happens is because the ssh url is used.
https://github.com/balisujohn/tortoise.cpp/blob/a7d8fae9bd0782bc9d58b1bac712815967403778/.gitmodules#L1-L3
Which requires to have an ssh key installed and setup with an github account. So without modifying the file upon cloning, you wont be able to.

It is usually best practice to use https for defaults, since it can be read without an account/needing identification.

**Comment by balisujohn** [comment]
I'll change to https.

**Comment by balisujohn** [comment]
Alright, the submodule is changed to https, and so is the recommended cloning command. This should work with or without a local SSH setup:

````
git clone --recursive https://github.com/balisujohn/tortoise.cpp.git
````
@trappedinspacetime 
Let me know if this fixes things for you; if I don't hear back in a little while, I'll assume it's fixed and close the issue.
