### ISSUE TITLE
can't found ggml-vocoder-model.bin

### ISSUE THREAD

**Issue by DickyQi** [balisujohn/tortoise.cpp#8]
after install and built, run with command line, then exit with no ggml-vocoder-model.bin file found error. where can download this file?

**Comment by fakerybakery** [comment]
It’s on huggingface (there’s an link in the readme)

**Comment by balisujohn** [comment]
I havent uploaded the vocoder model to hugging face yet, but I'm happy to upload it if you want to try out the current version of tue code. Though keep in mind I'm still working on the logic for the vocoder.

**Comment by DickyQi** [comment]
> I havent uploaded the vocoder model to hugging face yet, but I'm happy to upload it if you want to try out the current version of the code. Though keep in mind I'm still working on the logic for the vocoder.

Waiting for your great work.

**Comment by balisujohn** [comment]
Alright the models in the hugging face should be up to date :^)
